### PR TITLE
Spell correction

### PR DESCRIPTION
**Pull request by rabishah**

### CODE REVIEW

**Comment by rabishah** [comment]
Awesome library, just a minor bug :+1:

**Comment by jurca** [comment]
Will **somebody** merge this pull request?

This is necessary to make the module work under *nix systems.

**Comment by joelcoxokc** [comment]
Oh nice. Let me check it it real quick, and I'll merge.

**Comment by joelcoxokc** [comment]
@jurca Should be good to go!!

**Comment by jurca** [comment]
@joelcoxokc 
Great, thanks! Will you push the fix as 0.1.2 to the npm repository, please? (I can still see the 0.1.1 version here: https://www.npmjs.com/package/gulp-command)

**Comment by mjancarik** [comment]
Please update npm repository.

Thanks

**Comment by joelcoxokc** [comment]
I apologize. I will do here soon.

**Pull request merged**
